### PR TITLE
Adapt to newer versions of  pytorch-lightning

### LINKED ISSUE #4: dependency conflicts and interpretation.ipynb running error
Hi @yetinam thanks for updating the requirements. However, it still has conflicts(test in Google Colab and Mac OS 13.1):

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.5 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 1.8.1 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.8.1 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.8.1 which is incompatible.
```
Then I try running interpretation.ipynb , when importing packages  ` from benchmark import models`, the error is raised:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-4-b67497ed2a33>](https://localhost:8080/#) in <module>
      1 import torch
      2 import torch.nn.functional as F
----> 3 from benchmark import models
      4 import seisbench.data as sbd
      5 import seisbench.models as sbm

15 frames
[/usr/lib/python3.8/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 
    372         if handle is None:
--> 373             self._handle = _dlopen(self._name, mode)
    374         else:
    375             self._handle = handle

OSError: /usr/local/lib/python3.8/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
```

Same situation when running `train.py`

### PR DESCRIPTION
**Pull request by zhong-yy**
- Add a new requirement file,  `requirement-new-test.txt`. 
- Use `packaging.version.parse(pl.__version__)` to check the version of pytorch-lightning. For versions earlier than 1.7.0, use the original code
- For pytorch-lightning versions later than 1.7.0, make the following changes
    - Replace GPUStatsMonitor with DeviceStatsMonitor to fix (related to #3)
    - Correct the path to models (related to #5) 
    - Use a ModelCheckpoint callback explicitly to record the best model with the lowest validation loss (related to  #5) . 
        Reason: in the previous version,  the Trainer constructor creates a default ModelCheckpoint that monitors validation loss automatically, but this feature has been deprecated (see https://github.com/Lightning-AI/lightning/pull/6012 and https://github.com/Lightning-AI/lightning/pull/8293)
    - Record running time for training and evaluation 
    - Change the trainer argument: `gpus=1` to `accelerator="gpus", devices=1` ([Trainer#gpus](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#gpus)). 

The environment I used is
```
# Name                    Version                   Build  Channel
bayesian-optimization     1.4.2                    pypi_0    pypi
pytorch-lightning         1.9.0                    pypi_0    pypi
scikit-learn              1.2.1                    pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
seisbench                 0.2.8                    pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchmetrics              0.11.1                   pypi_0    pypi
```

### CODE REVIEW

**Comment by yetinam** [comment]
Hi @zhong-yy ,

thanks so much for picking this up. The PR looks pretty good. I only have two suggestions:
- I added a few changes to the main branch just now, mostly referring to the CI. Could you rebase your branch to main so that I the CI will pick it up?
- I'd suggest to skip the branching for the old version. Let's just have the new version and also replace the `requirements.txt` file with your file. There is a release at the version of the JGR paper, so people can without issues dig out the old version if required.

**Comment by yetinam** [comment]
Hi @zhong-yy ,

thanks so much for picking this up. The PR looks pretty good. I only have two suggestions:
- I added a few changes to the main branch just now, mostly referring to the CI. Could you rebase your branch to main so that I the CI will pick it up?
- I'd suggest to skip the branching for the old version. Let's just have the new version and also replace the `requirements.txt` file with your file. There is a release at the version of the JGR paper, so people can without issues dig out the old version if required.

**Comment by zhong-yy** [comment]
Hi, @yetinam Thank you for updating the code and reviewing the PR. I have removed the code that branches to the old version, and updated `requirements.txt`.

**Comment by zhong-yy** [comment]
May I ask what is the purpose of using GPUStatsMonitor or DeviceStatsMonitor in the code? I found the resulting metric.csv difficult to read, because there are too many items.

**Comment by yetinam** [comment]
Thanks for making these changes.

Regarding the GPUStatsMonitor, I added it to monitor the training but tbh I find the DeviceStatsMonitor also rather annoying and it really clutters the csv output. How about you comment it out so that whoever feels like using it can easily enable it again?

**Comment by zhong-yy** [comment]
The output looks better after commenting out the DeviceStatsMonitor

**Comment by yetinam** [comment]
Thanks again for the PR! I merged it now.

**Pull request merged**
